org: icpdao
app: icpdao
service: icpdao-interface

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: ${opt:stage}
  stackName: icpdao-interface-${self:provider.stage}
  deploymentBucket:
    name: icpdao.9527.${self:provider.region}.deploys

custom:
  s3Sync:
    - bucketName: ${env:WEBSITE_BUCKET_NAME}
      localDir: build
      deleteRemoved: false
      acl: public-read
      followSymlinks: true
      params:
        - index.html:
            CacheControl: 'no-cache'
        - "*.js":
            CacheControl: 'public, max-age=31536000'

plugins:
  - serverless-s3-sync

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:WEBSITE_BUCKET_NAME}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
  Outputs:
    WebsiteBucketOutputKey:
      Value: !Ref WebsiteBucket
