export default {
  'pages.home.mentor.warning.title': 'IN THE WORLF OF ICPDAO，EVERYONE WILL HAVE A MENTOR TO GUIDE',
  'pages.home.mentor.warning.p1.title': '<span style="color: #177DDC">WE BELIEVE</span>',
  'pages.home.mentor.warning.p1.content':
    'Everyone has the ability to contribute, it just needs to be the right project and the right way, even finding a bug can be rewarded',
  'pages.home.mentor.warning.p2.title': '<span style="color: #177DDC">NEED HELP</span>',
  'pages.home.mentor.warning.p2.content':
    "Everything is hard at first, and Mentor's core mission at ICPDAO is to help you find the right project, leverage your talents, and work with you whenever you need it.",
  'pages.home.mentor.warning.p3.title': '<span style="color: #177DDC">FIND A PERSON</span>',
  'pages.home.mentor.warning.p3.content':
    'The only thing you need to do is to find the right Mentor in ICPDAO.',
  'pages.home.mentor.welcome.title': 'WELCOME TO  ICPDAO',
  'pages.home.mentor.welcome.p1':
    '<span style="color: #177DDC">@{github_login}</span> is willing to be your Mentor and promises to help you, and will ask for help from TA\'s Mentor if he can\'t.',
  'pages.home.mentor.welcome.p2':
    "Congratulations !! you have officially entered the ICPDAO world and become a Pre-Icpper, once you have made a contribution or become someone's Mentor, you will automatically become a full Icpper!",
  'pages.home.mentor.welcome.p2.tooltip':
    'Icpper is a full member of the ICPDAO world, while Pre-Icpper is a new member who needs focused help.',
  'pages.home.mentor.welcome.p3':
    'Until then, you are one of the two people <span style="color: #177DDC">@{github_login}</span> cares about and helps the most.',
  'pages.home.mentor.welcome.p3.tooltip':
    'A Mentor can only support 2 Pre-Icppers at the same time',
  'pages.home.mentor.welcome.p4':
    'Please accept this help openly, and every time you contribute in the future, Mentor will also benefit.',
  'pages.home.mentor.welcome.p4.tooltip':
    "5% of each Icpper's contribution token reward will be used as Mentor reward and will be automatically assigned to its full superior Mentor (50%, 25%, 13%, 6%, 3%, 2%, 1%)",
  'pages.home.mentor.welcome.p5': 'I also hope you can become a Mentor and help others.',
  'pages.home.mentor.welcome.ok': "Okay, I accept Mentor's invitation",
  'pages.home.mentor.welcome.cancel': 'Let me think again',
  'pages.home.p1': 'Build and Fund the Open Web Together',
  'pages.home.p2':
    'Connect with the community that digitizes open source projects, creates inancial freedom, and defines the new network of open cooperation.',
  'pages.home.button1': 'EXPLORE DAO',
  'pages.home.button2': 'MARK JOB',
  'pages.account.icpper.preicpper': 'PRE-ICPPER',
  'pages.account.icpper.icpper': 'ICPPER',
  'pages.account.icpper.preicpper.tooltip': 'You are their mentor',
  'pages.account.icpper.icpper.tooltip': 'You are their mentor',
  'pages.account.icpper.input.invite.placeholder': 'Please enter the invitee github account',
  'pages.account.icpper.input.invite.time': 'Invited for {days}',
  'pages.account.icpper.input.invite.wait': 'Awaiting acceptance of invitation',
  'pages.account.icpper.input.invite.accept': 'Has become the PRE-ICPPER',
  'pages.account.icpper.invite': 'Invite',
  'pages.account.icpper.invite.cancel': 'Cancel',
  'pages.account.icpper.invite.model.p1':
    'You invite <span style="color: #177DDC">@{github_login}</span> into the world of ICPDAO and become its Mentor.',
  'pages.account.icpper.invite.model.p2':
    'You promise to help him or her as needed, and if you can\'t, you ask your own Mentor, <span style="color: #177DDC">@{github_login}</span>, for help.',
  'pages.account.icpper.invite.model.p2.nomentor': 'You promise to help him or her as needed.',
  'pages.account.icpper.invite.model.ok': 'Yes, I promise',
  'pages.account.icpper.invite.model.cancel': 'Let me think again',
  'pages.account.icpper.invite.cancel.model.p1':
    'Are you sure you want to terminate your Mentor relationship with <span style="color: #177DDC">@{github_login}</span>?',
  'pages.account.icpper.invite.cancel.model.p2':
    ' Once terminated, all contributions generated by <span style="color: #177DDC">@{github_login}</span> will no longer be rewarded, including all of his subordinates',
  'pages.account.icpper.invite.cancel.model.ok': "Yes, I'm sure",
  'pages.account.icpper.invite.cancel.model.cancel': 'Let me think again',
  'pages.account.icpper.table.column.1': 'No.',
  'pages.account.icpper.table.column.2': 'Nickname',
  'pages.account.icpper.table.column.3': 'Accepted time',
  'pages.account.icpper.table.column.4': 'Be a mentor (days)',
  'pages.account.icpper.table.column.5': 'Income',
  'pages.account.icpper.table.column.5.text': 'tokens',
  'pages.account.icpper.table.column.6': 'Operation',
  'pages.account.icpper.table.column.6.text': 'Release',
  'pages.account.mentor.table.column.1': 'Nickname',
  'pages.account.mentor.table.column.2': 'Github account',
  'pages.account.mentor.table.column.3': 'Number of instructors',
  'pages.account.wallet.tips':
    'PLEASE ENTER YOUR WALLET ADDRESS, SO WE KNOW WHERE TO SEND TOKEN TO YOU.',
  'pages.account.wallet.label': 'Wallet address :',
  'pages.account.wallet.save': 'SAVE',
  'pages.account.wallet.input.placeholder': '0xA23c75e32ae8Ee45cf76Cf23FBCcc0995acaEAEe',
  'pages.account.wallet.save.warning': 'invalid address',
  'pages.dao.config.tab.job': 'JOB',
  'pages.dao.config.tab.token': 'TOKEN',
  'pages.dao.config.tab.skip': 'skip',
  'pages.dao.config.tab.job.desc': 'PLEASE SET IT ACCORDING TO THE COMMUNITY.',
  'pages.dao.config.tab.job.form.timezone': 'Time Zone',
  'pages.dao.config.tab.job.form.deadline': 'Deadline for mark job',
  'pages.dao.config.tab.job.form.deadline.desc':
    'The minimum unit is month, please choose a suitable date or use the system date.',
  'pages.dao.config.tab.job.form.pairing': 'Pairing time',
  'pages.dao.config.tab.job.form.pairing.desc':
    'The minimum unit is day, please choose a suitable date or use the system date.',
  'pages.dao.config.tab.job.form.voting': 'Voting time',
  'pages.dao.config.tab.job.form.voting.desc':
    'The minimum unit is day, please choose a suitable date or use the system date.',
  'pages.dao.config.tab.job.form.ok': 'OK',
  'pages.dao.config.tab.job.form.save': 'SAVE',
  'pages.dao.config.tab.job.form.success': 'Success, DAO job config updated.',
  'pages.dao.home.view': 'VIEW ON GITHUB',
  'pages.dao.home.followed': 'FOLLOW',
  'pages.dao.home.unfollowed': 'UNFOLLOW',
  'pages.dao.home.created': ' Created',
  'pages.dao.home.following': ' following',
  'pages.dao.home.button.mark': 'Mark Job',
  'pages.dao.home.button.vote': 'Go Vote',
  'pages.dao.home.tab.icpper': 'Icpper',
  'pages.dao.home.tab.job': 'Job',
  'pages.dao.home.tab.cycle': 'Cycle',
};
