name: deploy

on:
  push:
    branches:
      - feature/*
      - fix/*
      - dev
      - prod

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

#      - name: test
#        env:
#          REACT_APP_GITHUB_APP_CLIENT_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_ID}}
#          REACT_APP_ICPDAO_BACKEND_BASE_URL: ${{secrets.DEV__REACT_APP_ICPDAO_BACKEND_BASE_URL}}
#          REACT_APP_ICPDAO_BACKEND_VERSION: "v1"
#          REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY: ${{secrets.DEV__REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY}}
#        run: |
#          yarn
#          yarn build

  deploy_dev:
    needs: [test]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
          REACT_APP_GITHUB_APP_CLIENT_ID: ${{secrets.DEV__ICPDAO_GITHUB_APP_CLIENT_ID}}
          REACT_APP_ICPDAO_BACKEND_BASE_URL: ${{secrets.DEV__REACT_APP_ICPDAO_BACKEND_BASE_URL}}
          REACT_APP_ICPDAO_BACKEND_VERSION: "v1"
          REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY: ${{secrets.DEV__REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY}}
          REACT_APP_ICPDAO_ETHEREUM_ALCHEMY_KEY: ${{secrets.DEV__REACT_APP_ICPDAO_ETHEREUM_ALCHEMY_KEY}}
          REACT_APP_ICPDAO_ETHEREUM_ETHERSCAN_KEY: ${{secrets.DEV__REACT_APP_ICPDAO_ETHEREUM_ETHERSCAN_KEY}}
          REACT_APP_ICPDAO_SENTRY_DSN: ${{secrets.DEV__REACT_APP_ICPDAO_SENTRY_DSN}}
          WEBSITE_BUCKET_NAME: ${{secrets.DEV__WEBSITE_BUCKET_NAME}}
        run: |
          npm install -g serverless
          yarn
          yarn build
          sls deploy --stage dev

  deploy_prod:
    needs: [test]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
          REACT_APP_GITHUB_APP_CLIENT_ID: ${{secrets.PROD__ICPDAO_GITHUB_APP_CLIENT_ID}}
          REACT_APP_ICPDAO_BACKEND_BASE_URL: ${{secrets.PROD__REACT_APP_ICPDAO_BACKEND_BASE_URL}}
          REACT_APP_ICPDAO_BACKEND_VERSION: "v1"
          WEBSITE_BUCKET_NAME: ${{secrets.PROD__WEBSITE_BUCKET_NAME}}
          REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY: ${{secrets.PROD__REACT_APP_ICPDAO_ETHEREUM_INFURA_KEY}}
          REACT_APP_ICPDAO_ETHEREUM_ALCHEMY_KEY: ${{secrets.PROD__REACT_APP_ICPDAO_ETHEREUM_ALCHEMY_KEY}}
          REACT_APP_ICPDAO_ETHEREUM_ETHERSCAN_KEY: ${{secrets.PROD__REACT_APP_ICPDAO_ETHEREUM_ETHERSCAN_KEY}}
          REACT_APP_ICPDAO_SENTRY_DSN: ${{secrets.PROD__REACT_APP_ICPDAO_SENTRY_DSN}}
        run: |
          npm install -g serverless
          yarn
          yarn build
          sls deploy --stage prod
